# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RxSwiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExample
  pod 'RxSwift',  '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'Alamofire', '~> 4.4'
  pod 'RxBlocking', '~> 3.0'
  pod 'RxTest', '~> 3.0'

  target 'RxSwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end


  target 'RxSwiftExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
